In [4]:
import os
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense, Conv2D, MaxPooling2D

In [5]:
positive_dir = './cracks-datasets/Positive/'
negative_dir = './cracks-datasets/Negative/'

In [6]:
pos_img_path = [img_path for img_path in os.listdir(positive_dir)]
neg_img_path = [img_path for img_path in os.listdir(negative_dir)]

In [9]:
pos_images = []

for img_path in pos_img_path:
    img = cv2.imread(f'{positive_dir}{img_path}')
    resize_img = cv2.resize(img, (64, 64))
    gray_img = cv2.cvtColor(resize_img, cv2.COLOR_BGR2GRAY)
    scaled_img = gray_img/255
    pos_images.append(scaled_img)

In [7]:
neg_images = []

for img_path in neg_img_path:
    img = cv2.imread(f'{negative_dir}{img_path}')
    resize_img = cv2.resize(img, (64, 64))
    gray_img = cv2.cvtColor(resize_img, cv2.COLOR_BGR2GRAY)
    scaled_img = gray_img/255
    neg_images.append(scaled_img)

In [10]:
print(len(pos_images))
print(len(neg_images))

20000
20000


In [11]:
X = np.array(pos_images + neg_images)

In [12]:
y = np.array([1] * len(pos_images) + [0] * len(neg_images))

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=1)

In [14]:
X_train.shape

(32000, 64, 64)

In [15]:
y_train.shape

(32000,)

In [80]:
model = Sequential()

model.add(Flatten(input_shape=(64, 64)))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=32, epochs=5)

Epoch 1/5
1000/1000 [==============================] - 81s 80ms/step - loss: 0.5150 - accuracy: 0.7726
Epoch 2/5
1000/1000 [==============================] - 79s 79ms/step - loss: 0.4051 - accuracy: 0.8562
Epoch 3/5
1000/1000 [==============================] - 80s 80ms/step - loss: 0.3768 - accuracy: 0.8688
Epoch 4/5
1000/1000 [==============================] - 80s 80ms/step - loss: 0.3579 - accuracy: 0.8804
Epoch 5/5
1000/1000 [==============================] - 79s 79ms/step - loss: 0.3512 - accuracy: 0.8808


In [81]:
loss, accuracy = model.evaluate(X_test, y_test)

250/250 [==============================] - 20s 79ms/step - loss: 0.3433 - accuracy: 0.8979


In [16]:
def get_preprocessed_img(img_path):
    img = cv2.imread(img_path)
    resize_img = cv2.resize(img, (64, 64))
    gray_img = cv2.cvtColor(resize_img, cv2.COLOR_BGR2GRAY)
    scaled_img = gray_img/255
    preprocessed_img = scaled_img.reshape(1, 64, 64)
    
    return preprocessed_img

In [17]:
pos_test_img_path = './cracks-datasets/Positive/00009.jpg';
neg_test_img_path = './cracks-datasets/Negative/10008.jpg';

pos_test_img = get_preprocessed_img(pos_test_img_path)
neg_test_img = get_preprocessed_img(neg_test_img_path)

In [18]:
pos_test_img.shape

(1, 64, 64)

In [19]:
model.predict([pos_test_img])

NameError: name 'model' is not defined

In [134]:
model.predict([neg_test_img])

1/1 [==============================] - 0s 144ms/step


array([[0.00019334]], dtype=float32)

In [92]:
model = Sequential()

model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=128, epochs=20)

Epoch 1/20
250/250 [==============================] - 20s 76ms/step - loss: 0.5925 - accuracy: 0.7445
Epoch 2/20
250/250 [==============================] - 19s 75ms/step - loss: 0.4653 - accuracy: 0.8410
Epoch 3/20
250/250 [==============================] - 20s 79ms/step - loss: 0.4230 - accuracy: 0.8596
Epoch 4/20
250/250 [==============================] - 19s 75ms/step - loss: 0.3952 - accuracy: 0.8721
Epoch 5/20
250/250 [==============================] - 19s 74ms/step - loss: 0.3878 - accuracy: 0.8690
Epoch 6/20
250/250 [==============================] - 19s 75ms/step - loss: 0.3728 - accuracy: 0.8787
Epoch 7/20
250/250 [==============================] - 19s 75ms/step - loss: 0.3599 - accuracy: 0.8857
Epoch 8/20
250/250 [==============================] - 19s 75ms/step - loss: 0.3537 - accuracy: 0.8903
Epoch 9/20
250/250 [==============================] - 20s 79ms/step - loss: 0.3497 - accuracy: 0.8901
Epoch 10/20
250/250 [==============================] - 19s 75ms/step - loss: 0.346

In [93]:
model = Sequential()

model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=64, epochs=20)

Epoch 1/20
500/500 [==============================] - 24s 46ms/step - loss: 0.5472 - accuracy: 0.7481
Epoch 2/20
500/500 [==============================] - 23s 46ms/step - loss: 0.4270 - accuracy: 0.8528
Epoch 3/20
500/500 [==============================] - 23s 46ms/step - loss: 0.3937 - accuracy: 0.8687
Epoch 4/20
500/500 [==============================] - 23s 46ms/step - loss: 0.3724 - accuracy: 0.8773
Epoch 5/20
500/500 [==============================] - 25s 50ms/step - loss: 0.3641 - accuracy: 0.8785
Epoch 6/20
500/500 [==============================] - 25s 49ms/step - loss: 0.3553 - accuracy: 0.8806
Epoch 7/20
500/500 [==============================] - 24s 48ms/step - loss: 0.3452 - accuracy: 0.8895
Epoch 8/20
500/500 [==============================] - 26s 51ms/step - loss: 0.3501 - accuracy: 0.8824
Epoch 9/20
500/500 [==============================] - 25s 50ms/step - loss: 0.3363 - accuracy: 0.8925
Epoch 10/20
500/500 [==============================] - 25s 49ms/step - loss: 0.335

In [94]:
model = Sequential()

model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=32, epochs=5)

Epoch 1/5
1000/1000 [==============================] - 168s 166ms/step - loss: 0.4807 - accuracy: 0.7671
Epoch 2/5
1000/1000 [==============================] - 169s 169ms/step - loss: 0.3364 - accuracy: 0.8572
Epoch 3/5
1000/1000 [==============================] - 168s 168ms/step - loss: 0.3029 - accuracy: 0.8780
Epoch 4/5
1000/1000 [==============================] - 171s 171ms/step - loss: 0.2893 - accuracy: 0.8851
Epoch 5/5
1000/1000 [==============================] - 177s 177ms/step - loss: 0.2857 - accuracy: 0.8865


In [95]:
model = Sequential()

model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=128, epochs=20)

Epoch 1/20
250/250 [==============================] - 47s 180ms/step - loss: 0.6560 - accuracy: 0.6926
Epoch 2/20
250/250 [==============================] - 46s 184ms/step - loss: 0.3955 - accuracy: 0.8496
Epoch 3/20
250/250 [==============================] - 46s 182ms/step - loss: 0.3472 - accuracy: 0.8558
Epoch 4/20
250/250 [==============================] - 46s 182ms/step - loss: 0.3064 - accuracy: 0.8747
Epoch 5/20
250/250 [==============================] - 46s 182ms/step - loss: 0.3003 - accuracy: 0.8783
Epoch 6/20
250/250 [==============================] - 45s 181ms/step - loss: 0.2923 - accuracy: 0.8836
Epoch 7/20
250/250 [==============================] - 48s 191ms/step - loss: 0.2810 - accuracy: 0.8879
Epoch 8/20
250/250 [==============================] - 46s 185ms/step - loss: 0.2501 - accuracy: 0.9045
Epoch 9/20
250/250 [==============================] - 44s 177ms/step - loss: 0.2365 - accuracy: 0.9095
Epoch 10/20
250/250 [==============================] - 45s 182ms/step - l

In [101]:
model = Sequential()

model.add(Conv2D(32, kernel_size=(3,3), strides=(1,1), padding='valid', input_shape=(64, 64, 1)))
model.add(MaxPooling2D(pool_size=(2,2), strides=(1,1)))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=32, epochs=5)

Epoch 1/5
1000/1000 [==============================] - 305s 303ms/step - loss: 0.3038 - accuracy: 0.8902
Epoch 2/5
1000/1000 [==============================] - 266s 266ms/step - loss: 0.1879 - accuracy: 0.9390
Epoch 3/5
1000/1000 [==============================] - 265s 265ms/step - loss: 0.1654 - accuracy: 0.9482
Epoch 4/5
1000/1000 [==============================] - 265s 265ms/step - loss: 0.1542 - accuracy: 0.9504
Epoch 5/5
1000/1000 [==============================] - 265s 265ms/step - loss: 0.1446 - accuracy: 0.9554


In [20]:
model = Sequential()

model.add(Conv2D(32, kernel_size=(3,3), activation='relu', input_shape=(64, 64, 1)))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(64, kernel_size=(3,3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(128, kernel_size=(3,3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=64, epochs=5)

Epoch 1/5
500/500 [==============================] - 304s 600ms/step - loss: 0.1042 - accuracy: 0.9605
Epoch 2/5
500/500 [==============================] - 300s 601ms/step - loss: 0.0411 - accuracy: 0.9881
Epoch 3/5
500/500 [==============================] - 312s 624ms/step - loss: 0.0362 - accuracy: 0.9895
Epoch 4/5
500/500 [==============================] - 298s 595ms/step - loss: 0.0234 - accuracy: 0.9928
Epoch 5/5
500/500 [==============================] - 294s 587ms/step - loss: 0.0180 - accuracy: 0.9946


In [110]:
model.evaluate(X_test, y_test)

250/250 [==============================] - 38s 151ms/step - loss: 0.0107 - accuracy: 0.9962


[0.010657215490937233, 0.9962499737739563]

In [149]:
pos_test_img_path = './cracks-datasets/Positive/00510.jpg';
neg_test_img_path = './cracks-datasets/Negative/10054.jpg';

pos_test_img = get_preprocessed_img(pos_test_img_path)
neg_test_img = get_preprocessed_img(neg_test_img_path)

In [150]:
model.predict([pos_test_img])

1/1 [==============================] - 0s 148ms/step


array([[1.]], dtype=float32)

In [146]:
model.predict([neg_test_img])

1/1 [==============================] - 0s 215ms/step


array([[0.00028456]], dtype=float32)

In [158]:
model.predict(X_test[5001].reshape(1, 64, 64))

1/1 [==============================] - 0s 149ms/step


array([[0.00045212]], dtype=float32)

In [196]:
pos_test_img_path = './test-img/pos-1.jfif';
# pos_test_img_path = './test-img/pos-2.jpg';
# pos_test_img_path = './test-img/pos-3.jfif';
# pos_test_img_path = './test-img/pos-4.webp';
# pos_test_img_path = './test-img/pos-5.png';


neg_test_img_path = './test-img/neg-1.jfif';


pos_test_img = get_preprocessed_img(pos_test_img_path)
# neg_test_img = get_preprocessed_img(neg_test_img_path)

In [197]:
model.predict(pos_test_img)

1/1 [==============================] - 0s 127ms/step


array([[1.]], dtype=float32)

In [190]:
model.predict(neg_test_img)

1/1 [==============================] - 0s 178ms/step


array([[0.00056521]], dtype=float32)

In [1]:
print("hello")

hello


In [24]:
img = X_test[5]


cv2.imshow("test", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [225]:
img.shape

(1, 64, 64)

In [199]:
print(pred)

[[1.]]


In [215]:
pos_test_img_path = './test-img/pos-1.jfif';
pos_test_img = get_preprocessed_img(pos_test_img_path)


pred = model.predict(pos_test_img)

mask = (np.squeeze(pred) > 0.5).astype(np.uint8) * 255
mask = mask.astype(np.uint8)

print("Mask dtype:", mask.dtype)
print("Mask shape:", mask.shape)
print("Mask unique values:", np.unique(mask))

image = cv2.imread(pos_test_img_path)

contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
for cnt in contours:
    x, y, w, h = cv2.boundingRect(cnt)
    cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)
    
print(contours)
    
cv2.imshow("Detected Crack", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

1/1 [==============================] - 0s 165ms/step
Mask dtype: uint8
Mask shape: ()
Mask unique values: [255]


error: OpenCV(4.11.0) :-1: error: (-5:Bad argument) in function 'findContours'
> Overload resolution failed:
>  - image is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'image'


In [35]:
import cv2
import numpy as np

def sliding_window(image, step_size, window_size):
    for y in range(0, image.shape[0] - window_size[1] + 1, step_size):
        for x in range(0, image.shape[1] - window_size[0] + 1, step_size):
            yield (x, y, image[y:y + window_size[1], x:x + window_size[0]])

# Load and prepare test image
image = cv2.imread('./test-img/pos-1.jfif')
image = cv2.resize(image, (256, 256))
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
normalized = gray / 255.0

window_size = (64, 64)
step_size = 16  # Overlapping windows for better coverage

for (x, y, window) in sliding_window(normalized, step_size, window_size):
    patch = window.reshape(1, 64, 64, 1)  # Add batch and channel dimensions
    pred = model.predict(patch, verbose=0)[0][0]
    if pred > 0.5:
        cv2.rectangle(image, (x, y), (x + 64, y + 64), (0, 255, 0), 2)

cv2.imshow("Detected Crack Regions", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [34]:
import cv2
import numpy as np

def sliding_window(image, step_size, window_size):
    for y in range(0, image.shape[0] - window_size[1] + 1, step_size):
        for x in range(0, image.shape[1] - window_size[0] + 1, step_size):
            yield (x, y, image[y:y + window_size[1], x:x + window_size[0]])

# Load and prepare test image
image = cv2.imread('./test-img/pos-3.jfif')
image = cv2.resize(image, (256, 256))
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
normalized = gray / 255.0

window_size = (64, 64)
step_size = 16

crack_boxes = []

for (x, y, window) in sliding_window(normalized, step_size, window_size):
    patch = window.reshape(1, 64, 64, 1)
    pred = model.predict(patch, verbose=0)[0][0]
    if pred > 0.5:
        crack_boxes.append((x, y, x + 64, y + 64))

# Merge all detected boxes into one bounding box
if crack_boxes:
    x1 = min(box[0] for box in crack_boxes)
    y1 = min(box[1] for box in crack_boxes)
    x2 = max(box[2] for box in crack_boxes)
    y2 = max(box[3] for box in crack_boxes)
    cv2.rectangle(image, (x1, y1), (x2, y2), (0, 255, 0), 2)

cv2.imshow("Detected Crack Region", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [30]:
import cv2
import numpy as np

# Load original image
image = cv2.imread('./test-img/pos-1.jfif')
input_image = cv2.resize(image, (256, 256))
gray = cv2.cvtColor(input_image, cv2.COLOR_BGR2GRAY)
normalized = gray / 255.0
input_tensor = normalized.reshape(1, 64, 64, 1)

# Predict mask
pred = model.predict(input_tensor, verbose=0)[0, :, :, 0]

# Threshold the prediction
mask = (pred > 0.5).astype(np.uint8) * 255

# Find contours on the mask
contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Draw one bounding box around the largest contour (or all combined)
if contours:
    all_points = np.concatenate(contours)
    x, y, w, h = cv2.boundingRect(all_points)
    cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)

cv2.imshow("Crack Detected", image)
cv2.waitKey(0)
cv2.destroyAllWindows()


ValueError: cannot reshape array of size 65536 into shape (1,64,64,1)